### ISSUE TITLE
Travellers font siduda meie htmliga + open sans

### ISSUE THREAD

**Issue by kristjanjansen** [kuressaareametikool/festival#2]

**Comment by ooker** [comment]
Travelsi asemel sai pealkirjadele laulupidu.ee põhjal Montserrat. Bodytekstiks Open Sans.

**Comment by ooker** [comment]
Lisasin niisiis siiski ka TTTravelsi top headeri pealkirja jaoks. Failid olemas fonts kaustas + imporditud css-i. 
font-family: 'TTTravels', sans-serif; peaks t;;tama
